INFO | 2021-05-14 01:42:46,735 | C:\Users\Azat\youtube\content\views.py changed, reloading.
INFO | 2021-05-14 01:51:13,320 | C:\Users\Azat\youtube\content\views.py changed, reloading.
INFO | 2021-05-14 11:49:39,865 | C:\Users\Azat\youtube\authentication\__init__.py changed, reloading.
INFO | 2021-05-14 11:50:44,363 | C:\Users\Azat\youtube\authentication\apps.py changed, reloading.
INFO | 2021-05-14 11:52:34,949 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
ERROR | 2021-05-14 11:53:24,920 | Internal Server Error: /auth/register
Traceback (most recent call last):
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\authentication\views.py", line 29, in create
    serializer.save()
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Users\Azat\youtube\authentication\serializers.py", line 31, in create
    return User.objects.create_user(
  File "C:\Users\Azat\youtube\authentication\managers.py", line 26, in create_user
    return self._create_user(email, password, **extra_fields)
  File "C:\Users\Azat\youtube\authentication\managers.py", line 20, in _create_user
    user.save(using=self._db)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\db\models\base.py", line 750, in save_base
    pre_save.send(
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\dispatch\dispatcher.py", line 180, in send
    return [
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\dispatch\dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
TypeError: user_created() missing 1 required positional argument: 'create'
INFO | 2021-05-14 11:53:44,573 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
INFO | 2021-05-14 11:53:48,228 | User (User Test) has been created
INFO | 2021-05-14 11:54:12,972 | User (User Test) has been deleted
WARNING | 2021-05-14 11:55:18,147 | Not Found: /favicon.ico
INFO | 2021-05-14 11:55:32,595 | User (User Test) has been created
INFO | 2021-05-14 11:55:54,245 | User (User Test) has been deleted
WARNING | 2021-05-14 11:55:58,613 | Unauthorized: /auth/users/me
INFO | 2021-05-14 11:56:41,370 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
INFO | 2021-05-14 11:57:27,929 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
INFO | 2021-05-14 11:57:34,163 | User (User Test) has been created
INFO | 2021-05-14 11:57:45,746 | User (User Test) has been deleted
WARNING | 2021-05-14 11:57:49,086 | Unauthorized: /auth/users/me
INFO | 2021-05-14 11:58:14,764 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
INFO | 2021-05-14 11:58:18,312 | User (User Test) has been created
INFO | 2021-05-14 11:58:28,609 | User (User Test) has been deleted
WARNING | 2021-05-14 12:02:27,305 | Unauthorized: /app/channels
INFO | 2021-05-14 12:23:20,755 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
INFO | 2021-05-14 12:23:37,021 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
INFO | 2021-05-14 12:23:42,389 | User (User Test) has been created
INFO | 2021-05-14 12:23:56,576 | User (User2 NEW) has been updated
INFO | 2021-05-14 12:24:51,629 | C:\Users\Azat\youtube\authentication\signals.py changed, reloading.
INFO | 2021-05-14 12:25:23,793 | User (User2 NEW) has been deleted
WARNING | 2021-05-14 12:26:03,303 | Unauthorized: /app/channels
INFO | 2021-05-14 12:27:51,412 | Channel (Channel) has been updated
WARNING | 2021-05-14 12:29:21,794 | Not Found: /media/avatars/channel/
WARNING | 2021-05-14 12:29:27,535 | Not Found: /media/
WARNING | 2021-05-14 12:29:30,509 | Not Found: /media/
INFO | 2021-05-14 12:44:06,042 | C:\Users\Azat\youtube\youtube\settings.py changed, reloading.
INFO | 2021-05-14 12:44:55,651 | C:\Users\Azat\youtube\youtube\urls.py changed, reloading.
INFO | 2021-05-14 12:45:04,230 | C:\Users\Azat\youtube\youtube\urls.py changed, reloading.
INFO | 2021-05-14 12:47:01,266 | C:\Users\Azat\youtube\youtube\settings.py changed, reloading.
INFO | 2021-05-14 12:47:37,129 | C:\Users\Azat\youtube\youtube\settings.py changed, reloading.
WARNING | 2021-05-14 12:47:51,396 | Bad Request: /app/channels/me
WARNING | 2021-05-14 12:47:51,612 | Not Found: /favicon.ico
INFO | 2021-05-14 13:49:37,154 | C:\Users\Azat\youtube\youtube\urls.py changed, reloading.
INFO | 2021-05-14 13:51:07,558 | C:\Users\Azat\youtube\youtube\settings.py changed, reloading.
WARNING | 2021-05-14 18:10:02,911 | Bad Request: /auth/login
INFO | 2021-05-14 18:14:03,499 | Channel (Channel) has been updated
INFO | 2021-05-14 18:17:08,706 | C:\Users\Azat\youtube\applications\apps.py changed, reloading.
INFO | 2021-05-14 18:18:37,458 | C:\Users\Azat\youtube\applications\signals.py changed, reloading.
INFO | 2021-05-14 18:53:50,764 | Channel (Channel) has been updated
ERROR | 2021-05-14 18:54:15,899 | Internal Server Error: /app/channels/me
Traceback (most recent call last):
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\applications\views.py", line 88, in update
    serializer.save()
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\serializers.py", line 200, in save
    self.instance = self.update(self.instance, validated_data)
  File "C:\Users\Azat\youtube\applications\serializers.py", line 23, in update
    instance.save()
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\db\models\base.py", line 750, in save_base
    pre_save.send(
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\dispatch\dispatcher.py", line 180, in send
    return [
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\dispatch\dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "C:\Users\Azat\youtube\applications\signals.py", line 12, in channel_changed
    avatar_delete(instance.avatar)
  File "C:\Users\Azat\youtube\tools\upload.py", line 6, in avatar_delete
    os.remove(avatar_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Azat\\youtube\\media\\photo.jpg'
ERROR | 2021-05-14 20:04:42,378 | Internal Server Error: /app/contents/me/nlhKjdVaS3uJjFtb
Traceback (most recent call last):
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\content\views.py", line 181, in update
    logging.info('User Channel (' + request.user.channel + ') updated the Content (' + content[0] + ')')
TypeError: can only concatenate str (not "Channel") to str
INFO | 2021-05-14 20:05:28,143 | C:\Users\Azat\youtube\content\views.py changed, reloading.
ERROR | 2021-05-14 20:05:31,675 | Internal Server Error: /app/contents/me/nlhKjdVaS3uJjFtb
Traceback (most recent call last):
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Azat\youtube\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Azat\youtube\content\views.py", line 181, in update
    logging.info('User Channel (' + request.user.channel.__str__() +
TypeError: can only concatenate str (not "VideoContent") to str
INFO | 2021-05-14 20:05:46,262 | C:\Users\Azat\youtube\content\views.py changed, reloading.
INFO | 2021-05-14 20:05:52,189 | User Channel (#GfG8zQfc8Wltaa6g (Channel)) updated the Content (#nlhKjdVaS3uJjFtb (NEW Title))
INFO | 2021-05-14 20:06:27,464 | C:\Users\Azat\youtube\content\apps.py changed, reloading.
INFO | 2021-05-14 20:06:32,376 | User Channel (#GfG8zQfc8Wltaa6g (Channel)) updated the Content (#nlhKjdVaS3uJjFtb (NEW Title))
INFO | 2021-05-14 20:06:42,438 | User Channel (#GfG8zQfc8Wltaa6g (Channel)) updated the Content (#nlhKjdVaS3uJjFtb (NEW Title))
INFO | 2021-05-14 20:07:25,376 | User Channel (#GfG8zQfc8Wltaa6g (Channel)) updated the Content (#nlhKjdVaS3uJjFtb (NEW Title))
INFO | 2021-05-14 20:07:49,634 | User Channel (#GfG8zQfc8Wltaa6g (Channel)) updated the Content (#nlhKjdVaS3uJjFtb (NEW Title))
INFO | 2021-05-14 20:08:10,960 | C:\Users\Azat\youtube\content\apps.py changed, reloading.
INFO | 2021-05-14 20:08:19,710 | User Channel (#GfG8zQfc8Wltaa6g (Channel)) updated the Content (#nlhKjdVaS3uJjFtb (NEW Title))
INFO | 2021-05-14 20:08:41,205 | User Channel (#GfG8zQfc8Wltaa6g (Channel)) updated the Content (#nlhKjdVaS3uJjFtb (NEW Title))
INFO | 2021-05-14 20:10:24,409 | C:\Users\Azat\youtube\applications\signals.py changed, reloading.
INFO | 2021-05-14 20:14:02,417 | C:\Users\Azat\youtube\applications\signals.py changed, reloading.
INFO | 2021-05-14 20:16:08,813 | C:\Users\Azat\youtube\content\signals.py changed, reloading.
INFO | 2021-05-14 20:30:32,818 | C:\Users\Azat\youtube\content\managers.py changed, reloading.
INFO | 2021-05-14 20:46:34,465 | C:\Users\Azat\youtube\content\managers.py changed, reloading.
INFO | 2021-05-14 20:53:24,441 | C:\Users\Azat\youtube\applications\managers.py changed, reloading.
INFO | 2021-05-14 20:59:44,088 | C:\Users\Azat\youtube\content\managers.py changed, reloading.
INFO | 2021-05-14 21:06:14,250 | C:\Users\Azat\youtube\content\models.py changed, reloading.
INFO | 2021-05-14 21:07:17,771 | C:\Users\Azat\youtube\content\models.py changed, reloading.
INFO | 2021-05-14 21:07:58,587 | C:\Users\Azat\youtube\content\managers.py changed, reloading.
WARNING | 2021-05-14 22:01:44,375 | Unauthorized: /auth/users/1
INFO | 2021-05-14 22:35:17,600 | C:\Users\Azat\youtube\content\managers.py changed, reloading.
INFO | 2021-05-14 22:46:46,589 | C:\Users\Azat\youtube\content\managers.py changed, reloading.
INFO | 2021-05-14 22:52:58,206 | C:\Users\Azat\youtube\applications\serializers.py changed, reloading.
INFO | 2021-05-14 22:54:08,967 | C:\Users\Azat\youtube\applications\serializers.py changed, reloading.
INFO | 2021-05-14 22:57:13,769 | C:\Users\Azat\youtube\authentication\serializers.py changed, reloading.
INFO | 2021-05-14 23:02:36,895 | C:\Users\Azat\youtube\authentication\serializers.py changed, reloading.
INFO | 2021-05-14 23:18:58,214 | C:\Users\Azat\youtube\content\serializers.py changed, reloading.
INFO | 2021-05-14 23:39:46,209 | C:\Users\Azat\youtube\content\serializers.py changed, reloading.
INFO | 2021-05-14 23:42:26,383 | C:\Users\Azat\youtube\additional\serializers.py changed, reloading.
INFO | 2021-05-14 23:47:55,083 | C:\Users\Azat\youtube\additional\serializers.py changed, reloading.
INFO | 2021-05-14 23:50:11,613 | C:\Users\Azat\youtube\additional\serializers.py changed, reloading.
INFO | 2021-05-14 23:52:18,021 | C:\Users\Azat\youtube\additional\serializers.py changed, reloading.
INFO | 2021-05-14 23:54:42,832 | C:\Users\Azat\youtube\additional\serializers.py changed, reloading.
INFO | 2021-05-14 23:56:40,589 | C:\Users\Azat\youtube\additional\serializers.py changed, reloading.
WARNING | 2021-05-15 00:07:02,421 | Not Found: /favicon.ico
